<?php
/**
 * ShortProductTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swappy
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swappy REST API
 *
 * This is Swappy's REST API. See below for all available endpoints. This is an <strong>alpha version</strong> and might still be subject to change
 *
 * OpenAPI spec version: 0.1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swappy;

/**
 * ShortProductTest Class Doc Comment
 *
 * @category    Class */
// * @description ShortProduct
/**
 * @package     Swappy
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShortProductTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ShortProduct"
     */
    public function testShortProduct()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "seller"
     */
    public function testPropertySeller()
    {

    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {

    }

    /**
     * Test attribute "images"
     */
    public function testPropertyImages()
    {

    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {

    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "auction"
     */
    public function testPropertyAuction()
    {

    }

    /**
     * Test attribute "date_end"
     */
    public function testPropertyDateEnd()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "live"
     */
    public function testPropertyLive()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "starting_price"
     */
    public function testPropertyStartingPrice()
    {

    }

    /**
     * Test attribute "reserve_price"
     */
    public function testPropertyReservePrice()
    {

    }

    /**
     * Test attribute "buynow_price"
     */
    public function testPropertyBuynowPrice()
    {

    }

    /**
     * Test attribute "lot_number"
     */
    public function testPropertyLotNumber()
    {

    }

    /**
     * Test attribute "delivery"
     */
    public function testPropertyDelivery()
    {

    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {

    }

    /**
     * Test attribute "auto_renew"
     */
    public function testPropertyAutoRenew()
    {

    }

    /**
     * Test attribute "taxes"
     */
    public function testPropertyTaxes()
    {

    }

    /**
     * Test attribute "estimate"
     */
    public function testPropertyEstimate()
    {

    }

    /**
     * Test attribute "offer"
     */
    public function testPropertyOffer()
    {

    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {

    }

}
